### ISSUE TITLE
Marked for installation on an Intel System76 laptop?

### ISSUE THREAD

**Issue by Raizex** [pop-os/amd-ppt-bin#1]
Ran `sudo apt-get upgrade` on an Intel based System76 laptop (Oryx Pro, Third? Generation) running Pop-OS version 20.04 (focal). This package was marked for installation under new packages to be installed.

Should this be the case? The repository description seems to indicate that it should only be installed on AMD based laptops.

**Comment by mgcox2** [comment]
Same issue with my ThinkPad X1. Putting the package on hold for now...

**Comment by jackpot51** [comment]
It's installed and inactive on any System76 laptops using system76-driver-nvidia. You can safely keep it, or remove it.
